# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExperimentApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExperimentApp

  target 'ExperimentAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExperimentAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry'
pod 'MJExtension'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDWebImage/GIF’
pod 'SDCycleScrollView'
pod 'MJRefresh'

end
