# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExperimentApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExperimentApp

  target 'ExperimentAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExperimentAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry', '~> 1.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'SDWebImage/GIF'
pod 'SDCycleScrollView', '~> 1.73'
pod 'MJRefresh', '~> 3.1.14.1'
pod 'MCDownloader', '~> 1.0.0'
pod 'SSKeychain', '~> 1.4.1'
end
